
services:
  PGVector:
    image: pgvector/pgvector:pg15

    container_name: Vector_db

    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data\

volumes:
  pgdata: